// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.4.7
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_codegen.cpp:451

#ifndef _TAO_IDL__HOME_JOEBP_WORKSPACE_CORBA_TAO_TAO_CALC_CALC_SRC_MAIN_CPP_CALCS_N8D6UA_H_
#define _TAO_IDL__HOME_JOEBP_WORKSPACE_CORBA_TAO_TAO_CALC_CALC_SRC_MAIN_CPP_CALCS_N8D6UA_H_


#include "CalcC.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/UB_String_SArguments.h"
#include "tao/PortableServer/get_arg.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

// TAO_IDL - Generated from
// /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:145

#if !defined (_BR_ORG_JOE_CALC__SARG_TRAITS_)
#define _BR_ORG_JOE_CALC__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::br::org::joe::Calc>
    : public
        Object_SArg_Traits_T<
            ::br::org::joe::Calc_ptr,
            ::br::org::joe::Calc_var,
            ::br::org::joe::Calc_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:35

namespace POA_br
{
  

  // TAO_IDL - Generated from
  // /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:35

  namespace org
  {
    

    // TAO_IDL - Generated from
    // /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:35

    namespace joe
    {
      

      // TAO_IDL - Generated from
      // /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_visitor_interface/interface_sh.cpp:73

      class Calc;
      typedef Calc *Calc_ptr;

      class  Calc
        : public virtual PortableServer::ServantBase
      {
      protected:
        Calc (void);
      
      public:
        /// Useful for template programming.
        typedef ::br::org::joe::Calc _stub_type;
        typedef ::br::org::joe::Calc_ptr _stub_ptr_type;
        typedef ::br::org::joe::Calc_var _stub_var_type;

        Calc (const Calc& rhs);
        virtual ~Calc (void);

        virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

        virtual void _dispatch (
            TAO_ServerRequest & req,
            TAO::Portable_Server::Servant_Upcall *servant_upcall);
        
        ::br::org::joe::Calc *_this (void);
        
        virtual const char* _interface_repository_id (void) const;

        // TAO_IDL - Generated from
        // /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:36

        virtual ::CORBA::Double doCalc (
          ::CORBA::Double value) = 0;

        static void doCalc_skel (
            TAO_ServerRequest &server_request,
            TAO::Portable_Server::Servant_Upcall *servant_upcall,
            TAO_ServantBase *servant);

        // TAO_IDL - Generated from
        // /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_visitor_operation/operation_sh.cpp:36

        virtual void shutdown (
          void) = 0;

        static void shutdown_skel (
            TAO_ServerRequest &server_request,
            TAO::Portable_Server::Servant_Upcall *servant_upcall,
            TAO_ServantBase *servant);
      };
    
    // TAO_IDL - Generated from
    // /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:66

    } // module br::org::joe
  
  // TAO_IDL - Generated from
  // /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:66

  } // module br::org

// TAO_IDL - Generated from
// /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:66

} // module br

#endif /* ifndef */

