// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.4.7
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_codegen.cpp:366


#include "CalcC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "CalcC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for br::org::joe::Calc.

br::org::joe::Calc_ptr
TAO::Objref_Traits<br::org::joe::Calc>::duplicate (
    br::org::joe::Calc_ptr p)
{
  return br::org::joe::Calc::_duplicate (p);
}

void
TAO::Objref_Traits<br::org::joe::Calc>::release (
    br::org::joe::Calc_ptr p)
{
  ::CORBA::release (p);
}

br::org::joe::Calc_ptr
TAO::Objref_Traits<br::org::joe::Calc>::nil (void)
{
  return br::org::joe::Calc::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<br::org::joe::Calc>::marshal (
    const br::org::joe::Calc_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:88

::CORBA::Double
br::org::joe::Calc::doCalc (
  ::CORBA::Double value)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< ::CORBA::Double>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Double>::in_arg_val _tao_value (value);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_value
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "doCalc",
      6,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _tao_call.invoke (0, 0);

  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:88

void
br::org::joe::Calc::shutdown (
  void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "shutdown",
      8,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY,
      TAO::TAO_ONEWAY_INVOCATION,
      TAO::TAO_SYNCHRONOUS_INVOCATION,
      false
    );

  _tao_call.invoke (0, 0);
}

br::org::joe::Calc::Calc (void)
{
}

br::org::joe::Calc::~Calc (void)
{
}

void
br::org::joe::Calc::_tao_any_destructor (void *_tao_void_pointer)
{
  Calc *_tao_tmp_pointer =
    static_cast<Calc *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

br::org::joe::Calc_ptr
br::org::joe::Calc::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<Calc>::narrow (
        _tao_objref,
        "IDL:br/org/joe/Calc:1.0");
}

br::org::joe::Calc_ptr
br::org::joe::Calc::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<Calc>::unchecked_narrow (
        _tao_objref);
}

br::org::joe::Calc_ptr
br::org::joe::Calc::_nil (void)
{
  return 0;
}

br::org::joe::Calc_ptr
br::org::joe::Calc::_duplicate (Calc_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
br::org::joe::Calc::_tao_release (Calc_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
br::org::joe::Calc::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:br/org/joe/Calc:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* br::org::joe::Calc::_interface_repository_id (void) const
{
  return "IDL:br/org/joe/Calc:1.0";
}

::CORBA::Boolean
br::org::joe::Calc::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_visitor_typecode/objref_typecode.cpp:70

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_br_org_joe_Calc (
    ::CORBA::tk_objref,
    "IDL:br/org/joe/Calc:1.0",
    "Calc");
  

namespace br
{
  
  namespace org
  {
    
    namespace joe
    {
      ::CORBA::TypeCode_ptr const _tc_Calc =
        &_tao_tc_br_org_joe_Calc;
    }
  }
}

// TAO_IDL - Generated from
// /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_visitor_interface/any_op_cs.cpp:38
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<br::org::joe::Calc>::to_object (
      ::CORBA::Object_ptr &_tao_elem) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace br
{
  
  namespace org
  {
    
    namespace joe
    {
      

      /// Copying insertion.
      void
      operator<<= (
          ::CORBA::Any &_tao_any,
          Calc_ptr _tao_elem)
      {
        Calc_ptr _tao_objptr =
          Calc::_duplicate (_tao_elem);
        _tao_any <<= &_tao_objptr;
      }

      /// Non-copying insertion.
      void
      operator<<= (
          ::CORBA::Any &_tao_any,
          Calc_ptr *_tao_elem)
      {
        TAO::Any_Impl_T<Calc>::insert (
            _tao_any,
            Calc::_tao_any_destructor,
            _tc_Calc,
            *_tao_elem);
      }

      ::CORBA::Boolean
      operator>>= (
          const ::CORBA::Any &_tao_any,
          Calc_ptr &_tao_elem)
      {
        return
          TAO::Any_Impl_T<Calc>::extract (
              _tao_any,
              Calc::_tao_any_destructor,
              _tc_Calc,
              _tao_elem);
      }
    }
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    br::org::joe::Calc_ptr _tao_elem)
{
  br::org::joe::Calc_ptr _tao_objptr =
    br::org::joe::Calc::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    br::org::joe::Calc_ptr *_tao_elem)
{
  TAO::Any_Impl_T<br::org::joe::Calc>::insert (
      _tao_any,
      br::org::joe::Calc::_tao_any_destructor,
      br::org::joe::_tc_Calc,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    br::org::joe::Calc_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<br::org::joe::Calc>::extract (
        _tao_any,
        br::org::joe::Calc::_tao_any_destructor,
        br::org::joe::_tc_Calc,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// /home/joebp/workspace/corba/ACE_TAO/TAO/TAO_IDL/be/be_visitor_interface/cdr_op_cs.cpp:51

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const br::org::joe::Calc_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    br::org::joe::Calc_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::br::org::joe::Calc RHS_SCOPED_NAME;

  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (obj.in ());
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



